#!/usr/bin/env python3
import os
from datetime import datetime

# Find all *.md files except README.md and 0-template.md
files = sorted([f for f in os.listdir() if f.endswith(".md") and f not in ["README.md", "0-template.md"]])

# Generate markdown table
table = "\n\n"
table += f"> Generated by `python3 update.py` @ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
table += "\n"
table += "| Document | Description |\n"
table += "|:---|:---|\n"

for file in files:
    with open(file, 'r') as f:
        lines = f.readlines()
        if lines:
            name = file.replace('.md', '')
            description = lines[0].lstrip('# ').strip()
            row = f"| [{file}]({file}) | {description} |\n"
            table += row

# Read the existing README.md content
with open('README.md', 'r') as readme_file:
    orig_readme = readme_file.read()

# Update content below ## Documents
start_index = orig_readme.find('## Documents') + len('## Documents')
end_index = orig_readme.find('##', start_index)
updated_readme = orig_readme[:start_index] + table + orig_readme[end_index:]

# Write the updated content back to README.md
with open('README.md', 'w') as readme_file:
    readme_file.write(updated_readme)

print("Table updated in README.md")
